FORK_ID = "gwine"

DEFINITION = {
    "name": "Gwine",
    "author": "elgabo86",
    "base": None,
    "branch": None,
    "wine_version": None,
    "dxvk": False,
    "vkd3d": False,
    "dxvk_nvapi": False,
    "features": {
        "wine_special_build": True,
    },
    "patches": [],
    "dll_overrides": {},
    "env_defaults": {},
    "ld_library_path_extra": [],
    "launch": {"method": "auto", "wineloadernoexec": False, "use_preloader": False},
    "notes": "Wine special build by elgabo86. No bundled DXVK/VKD3D. Container generic.",
    "container_overrides": {"ntsync": False, "nvidia_libs_bundled": False},
}


def get_container_config() -> dict:
    return {
        "audio": {
            "setup_alsa_config": False,
            "bind_pulse_socket": True,
            "bind_pipewire_socket": True,
            "pulse_cookie": True,
            "pulse_server": "unix:/run/user/1000/pulse/native",
            "pulse_clientconfig": "enable-shm=no",
            "alsoft_drivers": "pulse,alsa",
            "bind_dev_snd": False,
            "openal_i386": True,
            "bind_run_user": True,
        },
        "gpu": {
            "vendor": "auto",
            "skip_nvidia_overrides": False,
            "egl_vendor_nvidia_only": False,
            "glx_vendor": "",
            "vk_icd": "",
            "bind_dev_dri": True,
            "bind_dev_nvidia": True,
        },
        "display": {
            "bind_x11": True,
            "bind_wayland": True,
            "bind_dbus": True,
            "bind_discord": True,
            "xauthority": True,
            "wayland_display": "wayland-0",
            "display_env": ":0",
        },
        "container": {
            "unshare_all": False,
            "disable_userns": True,
            "clearenv": True,
            "cap_drop_all": True,
            "seccomp": True,
            "lock_file": True,
            "needs_ntsync_dev": False,
            "host_provider_mount": "/run/host",
            "home_isolation": "tmpfs",
            "runtime_mount": "/usr",
            "lib_mount": "/lib",
            "linkers": True,
            "bin_sbin_symlinks": True,
            "ld_so_cache": True,
            "pulse_config": True,
            "openal_config": True,
            "alsa_config_dir": True,
        },
        "devices": {
            "bind_snd": False,
            "bind_dri": True,
            "bind_nvidia": True,
            "bind_ntsync": False,
            "bind_shm": True,
            "bind_udev": True,
        },
        "mounts": {
            "host_provider": True,
            "proton_mount": "/proton",
        },
        "env": {
            "WINEDLLOVERRIDES": "winemenubuilder.exe=",
            "PROTON_CRASH_REPORT_DIR": "/tmp/proton_crashreports",
        },
    }
