FORK_ID = "umu-proton"

DEFINITION = {
    "name": 'UMU-Proton',
    "author": 'Open-Wine-Components',
    "base": 'valve',
    "branch": 'proton_10.0',
    "wine_version": None,
    "dxvk": True,
    "vkd3d": True,
    "dxvk_nvapi": True,
    "features": {
        "async": False,
        "dlss_upgrader": False,
        "fsr": False,
        "fsr4": False,
        "gamemode": False,
        "hdr": True,
        "local_shader_cache": False,
        "ntsync": False,
        "per_game_shader_cache": False,
        "raytracing": True,
        "wayland": True,
        "xess_upgrader": False,
    },
    "patches": ['umu_protonfixes', 'non_steam_focus'],
    "dll_overrides": {},
    "env_defaults": {},
    "ld_library_path_extra": [],
        "launch": {"method": "wine64", "wineloadernoexec": False, "use_preloader": False, "use_umu_exe": True},
    "notes": 'Stable branch focus. Designed for UMU-Launcher non-Steam games. Conservative.',
}
