FORK_ID = "dw-proton"

DEFINITION = {
    "name": 'DW-Proton (Dawn Winery)',
    "author": 'Dawn Winery (NelloKudo)',
    "base": 'proton-cachyos',
    "branch": None,
    "wine_version": None,
    "dxvk": True,
    "vkd3d": True,
    "dxvk_nvapi": True,
    "features": {
        "anticheat_optimizations": True,
        "async": False,
        "dlss_upgrader": True,
        "eac_improvements": True,
        "fsr": True,
        "fsr4": True,
        "gamemode": True,
        "hdr": True,
        "local_shader_cache": True,
        "miniloader_fixes": True,
        "ntsync": True,
        "per_game_shader_cache": True,
        "raytracing": True,
        "spritz_patches": True,
        "wayland": True,
        "winealsa": True,
        "xess_upgrader": True,
    },
    "patches": ['spritz_input_fix', 'spritz_disconnect_trick', 'spritz_timeout_fix', 'miniloader_fixes', 'eac_bypass', 'anticheat', 'media_playback', 'cachyos_base'],
    "dll_overrides": {},
    "env_defaults": {
        'PROTON_USE_WINEALSA': '0',
        'WINE_DISABLE_DISCONNECT': '0',
        'WINE_ENABLE_DISCONNECT': '0',
        'WINE_ENABLE_TIMEOUT_FIX': '0',
        'WINE_USE_TAKE_FOCUS': '0',
    },
    "ld_library_path_extra": [],
    "notes": 'Based on CachyOS Proton SLR. Spritz patches for input/alt-tab fixes, winealsa option, miniloader fixes. Best for NIKKE/anime games + anti-cheat.',
}
