FORK_ID = "proton-wine-andrevto"

DEFINITION = {
    "name": 'Proton-Wine (AndreVto)',
    "author": 'AndreVto',
    "base": 'valve',
    "branch": 'proton_11.0',
    "wine_version": None,
    "dxvk": True,
    "vkd3d": True,
    "dxvk_nvapi": True,
    "features": {
        "arm64ec": True,
        "async": False,
        "dlss_upgrader": False,
        "esync": True,
        "fsr": False,
        "fsr4": False,
        "fsync": True,
        "gamemode": False,
        "hdr": False,
        "local_shader_cache": False,
        "ntsync": False,
        "per_game_shader_cache": False,
        "raytracing": False,
        "wayland": False,
        "winlator_compat": True,
        "xess_upgrader": False,
    },
    "patches": ['proton_wine_source', 'esync', 'arm64ec_cross_compile'],
    "dll_overrides": {},
    "env_defaults": {},
    "ld_library_path_extra": [],
    "notes": 'Fork of GameNative/proton-wine. Proton Wine source with WCP output for Winlator. Based on Proton 11.0 beta.',
}
