FORK_ID = "proton-wine-gamenative"

DEFINITION = {
    "name": 'Proton-Wine (GameNative)',
    "author": 'GameNative',
    "base": 'valve',
    "branch": 'proton_11.0',
    "wine_version": None,
    "dxvk": True,
    "vkd3d": True,
    "dxvk_nvapi": True,
    "features": {
        "arm64ec": True,
        "async": False,
        "dlss_upgrader": False,
        "esync": True,
        "fsr": False,
        "fsr4": False,
        "fsync": True,
        "gamemode": False,
        "hdr": False,
        "local_shader_cache": False,
        "ntsync": False,
        "per_game_shader_cache": False,
        "raytracing": False,
        "wayland": False,
        "winlator_compat": True,
        "xess_upgrader": False,
    },
    "patches": ['proton_wine_source', 'esync', 'arm64ec_cross_compile'],
    "dll_overrides": {},
    "env_defaults": {},
    "ld_library_path_extra": [],
    "notes": "Fork of Valve's Proton Wine source without Proton scripts. Produces WCP files for Winlator/Android. ARM64EC support.",
}
