import { LibraryGame, SteamInstalledGame } from "@types";
import { ViewMode, SortOption } from "@renderer/pages/games/games-types";
import type { GameConfig } from "./components/modals/add-game/games-service";

export interface GamesPageState {
  searchQuery: string;
  setSearchQuery: (v: string) => void;
  viewMode: ViewMode;
  sortBy: SortOption;
  showAddModal: boolean;
  setShowAddModal: (v: boolean) => void;
  showConfigModal: boolean;
  setShowConfigModal: (v: boolean) => void;
  showDeleteModal: boolean;
  setShowDeleteModal: (v: boolean) => void;
  showBackupModal: boolean;
  setShowBackupModal: (v: boolean) => void;
  showBackupPanel: boolean;
  setShowBackupPanel: (v: boolean) => void;
  backupProvider: string | null;
  setBackupProvider: (v: string | null) => void;
  dllCheckModal: {
    open: boolean;
    loading: boolean;
    result: { installed: string[]; errors: string[] } | null;
  };
  setDllCheckModal: (v: {
    open: boolean;
    loading: boolean;
    result: { installed: string[]; errors: string[] } | null;
  }) => void;
  steamGames: SteamInstalledGame[];
  syncing: boolean;
  selectedSteamGame: SteamInstalledGame | null;
  showAllGames: boolean;
  erroredImages: Set<string>;
  clearingPrefix: boolean;
  steamFavoritedIds: Set<string>;
  gameContextMenu: {
    game: GameConfig | null;
    visible: boolean;
    position: { x: number; y: number };
  };
  filteredGames: GameConfig[];
  loading: boolean;
  loadGames: () => void;
  selectedGame: GameConfig | null;
  setSelectedGame: (v: GameConfig | null) => void;
  showHiddenGames: boolean;
  setShowHiddenGames: (v: boolean) => void;
  runningGameIds: Set<string>;
  launchingGameIds: Set<string>;
  playGame: (g: GameConfig) => void;
  stopGame: (g: GameConfig) => void;
  hideGame: (g: GameConfig) => void;
  favoriteGame: (g: GameConfig) => void;
  deleteGame: (g: GameConfig) => void;
  deleteGameWithPrefix: (g: GameConfig) => void;
  duplicateGame: (g: GameConfig) => void;
  addToSteam: (g: GameConfig) => void;
  createShortcut: (g: GameConfig) => void;
  revealFolder: (g: GameConfig) => void;
  revealWinePrefix: (g: GameConfig) => void;
  hasHiddenGames: boolean;
  handleSyncSteam: () => Promise<void>;
  handlePlaySteam: (game: SteamInstalledGame) => Promise<void>;
  handleWineTool: (tool: string) => void;
  handleFavoriteSteam: (game: SteamInstalledGame) => Promise<void>;
  handleConfigureGame: (game: GameConfig) => void;
  handleConfigureSteamGame: (game: SteamInstalledGame) => void;
  handleSaveGameConfig: (updatedGame: GameConfig, clearPrefix?: boolean) => Promise<void>;
  handleOpenSteamContextMenu: (game: SteamInstalledGame, position: { x: number; y: number }) => void;
  handleClearSteamPrefix: (game: SteamInstalledGame) => Promise<void>;
  handleClearLocalPrefix: (game: GameConfig) => Promise<void>;
  handleViewModeChange: (mode: ViewMode) => void;
  handleSortChange: (nextSortBy: SortOption) => void;
  handleSelectGame: (game: GameConfig) => void;
  handleSelectSteamGame: (game: SteamInstalledGame) => void;
  handleOpenContextMenu: (game: LibraryGame, position: { x: number; y: number }) => void;
  handleCloseContextMenu: () => void;
  handleImageError: (gameId: string) => void;
  filteredSteam: SteamInstalledGame[];
  localGames: GameConfig[];
  librarySteamGames: GameConfig[];
  hasSteamGames: boolean;
  hasLocalGames: boolean;
  hasLibrarySteamGames: boolean;
  showEmpty: boolean;
  showNoSearchResults: boolean;
  showLoading: boolean;
  activeGame: GameConfig | null;
  isSteamActive: boolean;
  isRunning: boolean;
  isLaunching: boolean;
  syncLabel: string;
  updateLibrary: () => Promise<void>;
}
