FORK_ID = "dw-proton"

DEFINITION = {
    "name": "DW-Proton",
    "author": "doitsujin",
    "base": "valve",
    "branch": "11.0-5",
    "wine_version": None,
    "dxvk": True,
    "vkd3d": True,
    "dxvk_nvapi": True,
    "features": {
        "async": False,
        "dlss_upgrader": True,
        "esync": True,
        "fsr": True,
        "fsr3": True,
        "fsr4": True,
        "gamemode": True,
        "local_shader_cache": True,
        "mlfg": True,
        "nvidia_nvml": True,
        "ntsync": True,
        "optiscaler": True,
        "per_game_shader_cache": True,
        "raytracing": True,
        "wayland": True,
        "xess_upgrader": True,
    },
    "patches": [
        'bolsacompiler', 'winewayland', 'dxvk_sarek', 'dxvk_llasync',
        'dxvk_gplasync', 'dxvk_low_latency', 'nvidia_libs_nvapi',
        'nvidia_libs_nvcuda', 'nvidia_libs_nvenc', 'nvidia_libs_nvml',
        'nvidia_libs_nvoptix', 'protonfixes', 'media_conversion',
        'fsr3_upgrade', 'fsr4_upgrade', 'dlss_upgrade', 'xess_upgrade',
        'ntsync', 'xalia', 'vk_low_latency_layer', 'vkbasalt', 'pyroveil',
        'discord_rpc_bridge',
    ],
    "dll_overrides": {
        "beclient.dll": "b,n",
        "beclient_x64.dll": "b,n",
        "lsteamclient": "d",
        "steam_api": "b",
        "steam_api64": "b",
        "opencl": "n,d",
        "winebth.sys": "d",
    },
    "env_defaults": {
        "WINEESYNC": "1",
        "WINEFSYNC": "1",
        "DXVK_ENABLE_NVAPI": "1",
        "__GLVND_DISALLOW_PATCHING": "1",
    },
    "ld_library_path_extra": [],
    "launch": {"method": "wine_preloader", "wineloadernoexec": True, "use_preloader": True},
    "notes": "doitsujin's DW-Proton. DXVK variants, NVIDIA NVAPI/CUDA/ENC/ML/OPTIX, winewayland, FSR3/4/DLSS/XeSS, media conversion, xalia, low latency layer, protonfixes.",
    "container_overrides": {"ntsync": True, "nvidia_libs_bundled": False},
}


def get_container_config() -> dict:
    """Container config for DW-Proton.

    DW-Proton usará libs NVIDIA do host (NVAPI, NVCUDA, NVENC, NVML, NVOPTIX)
    e precisa de /dev/snd para winealsa.drv quando PROTON_USE_WINEALSA for ativado.
    Tem winewayland.drv opcional, media conversion, xalia, e várias features.
    """
    return {
        "audio": {
            "setup_alsa_config": False,
            "asound_default": None,
            "bind_pulse_socket": True,
            "bind_pipewire_socket": True,
            "pulse_cookie": True,
            "pulse_server": "unix:/run/user/1000/pulse/native",
            "pulse_clientconfig": "enable-shm=no",
            "alsoft_drivers": "pulse,alsa",
            "bind_dev_snd": False,
            "openal_i386": True,
            "bind_run_user": True,
        },
        "gpu": {
            "vendor": "nvidia",
            "skip_nvidia_overrides": False,
            "egl_vendor_nvidia_only": True,
            "glx_vendor": "nvidia",
            "vk_icd": "nvidia",
            "dri_drivers_path": "",
            "gbm_backends_path": "",
            "bind_dev_dri": True,
            "bind_dev_nvidia": True,
        },
        "display": {
            "bind_x11": True,
            "bind_wayland": True,
            "bind_dbus": True,
            "bind_discord": True,
            "xauthority": True,
            "wayland_display": "wayland-0",
            "display_env": ":0",
            "xdg_session_type": "",
        },
        "container": {
            "unshare_all": False,
            "disable_userns": True,
            "clearenv": True,
            "cap_drop_all": True,
            "seccomp": True,
            "lock_file": True,
            "ld_library_path_extra": [],
            "needs_ntsync_dev": True,
            "host_provider_mount": "/run/host",
            "home_isolation": "tmpfs",
            "runtime_mount": "/usr",
            "lib_mount": "/lib",
            "linkers": True,
            "bin_sbin_symlinks": True,
            "ld_so_cache": True,
            "pulse_config": True,
            "openal_config": True,
            "alsa_config_dir": True,
        },
        "devices": {
            "bind_snd": False,
            "bind_dri": True,
            "bind_nvidia": True,
            "bind_ntsync": True,
            "bind_shm": True,
            "bind_udev": True,
            "extra_binds": [],
        },
        "mounts": {
            "host_provider": True,
            "proton_mount": "/proton",
        },
        "env": {
            "WINEDLLOVERRIDES": "winemenubuilder.exe=",
            "PROTON_CRASH_REPORT_DIR": "/tmp/proton_crashreports",
            "DXVK_ENABLE_NVAPI": "1",
            "WINEESYNC": "1",
            "WINEFSYNC": "1",
            "__GLVND_DISALLOW_PATCHING": "1",
            "GST_PLUGIN_SYSTEM_PATH_1_0": "",
            "GIO_EXTRA_MODULES": "/usr/lib/x86_64-linux-gnu/gio/modules:/usr/lib/i386-linux-gnu/gio/modules",
        },
    }
