FORK_ID = "proton-wine-andrevto"

DEFINITION = {
    "name": "Proton-Wine (AndreVto)",
    "author": "AndreVto",
    "base": "valve",
    "branch": "proton_11.0",
    "wine_version": None,
    "dxvk": True,
    "vkd3d": True,
    "dxvk_nvapi": True,
    "features": {
        "esync": True,
        "fsync": True,
    },
    "patches": ["proton_wine_source", "esync", "arm64ec_cross_compile"],
    "dll_overrides": {
        "beclient.dll": "b,n",
        "beclient_x64.dll": "b,n",
        "opencl": "n,d",
        "winebth.sys": "d",
    },
    "env_defaults": {
        "WINEESYNC": "1",
        "WINEFSYNC": "1",
        "DXVK_ENABLE_NVAPI": "1",
    },
    "ld_library_path_extra": [],
    "launch": {"method": "wine_preloader", "wineloadernoexec": True, "use_preloader": True},
    "notes": "Fork of GameNative/proton-wine. ARM64EC cross-compile. Primarily for Winlator (Android). Linux desktop works as Valve base.",
    "container_overrides": {"ntsync": False, "nvidia_libs_bundled": True},
}


def get_container_config() -> dict:
    return {
        "audio": {
            "setup_alsa_config": False,
            "bind_pulse_socket": True,
            "bind_pipewire_socket": True,
            "pulse_cookie": True,
            "pulse_server": "unix:/run/user/1000/pulse/native",
            "pulse_clientconfig": "enable-shm=no",
            "alsoft_drivers": "pulse,alsa",
            "bind_dev_snd": False,
            "openal_i386": True,
            "bind_run_user": True,
        },
        "gpu": {
            "vendor": "nvidia",
            "skip_nvidia_overrides": True,
            "egl_vendor_nvidia_only": True,
            "glx_vendor": "nvidia",
            "vk_icd": "nvidia",
            "bind_dev_dri": True,
            "bind_dev_nvidia": True,
        },
        "display": {
            "bind_x11": True,
            "bind_wayland": False,
            "bind_dbus": True,
            "bind_discord": True,
            "xauthority": True,
            "wayland_display": "",
            "display_env": ":0",
        },
        "container": {
            "unshare_all": False,
            "disable_userns": True,
            "clearenv": True,
            "cap_drop_all": True,
            "seccomp": True,
            "lock_file": True,
            "needs_ntsync_dev": False,
            "host_provider_mount": "/run/host",
            "home_isolation": "tmpfs",
            "runtime_mount": "/usr",
            "lib_mount": "/lib",
            "linkers": True,
            "bin_sbin_symlinks": True,
            "ld_so_cache": True,
            "pulse_config": True,
            "openal_config": True,
            "alsa_config_dir": True,
        },
        "devices": {
            "bind_snd": False,
            "bind_dri": True,
            "bind_nvidia": True,
            "bind_ntsync": False,
            "bind_shm": True,
            "bind_udev": True,
        },
        "mounts": {
            "host_provider": True,
            "proton_mount": "/proton",
        },
        "env": {
            "WINEDLLOVERRIDES": "winemenubuilder.exe=",
            "PROTON_CRASH_REPORT_DIR": "/tmp/proton_crashreports",
            "DXVK_ENABLE_NVAPI": "1",
            "WINEESYNC": "1",
            "WINEFSYNC": "1",
        },
    }
