AC_TYPE_INFO: dict[str, dict] = {
    "eac": {
        "name": "Easy Anti-Cheat",
        "env_var": "PROTON_EAC_ENABLE",
        "env_val": "1",
        "compatible_generally": True,
        "description": "Epic Games. Compatível quando dev ativa suporte Linux.",
    },
    "battleye": {
        "name": "BattlEye",
        "env_var": "PROTON_BATTLEYE_ENABLE",
        "env_val": "1",
        "compatible_generally": True,
        "description": "BattlEye. Compatível quando dev ativa suporte Linux.",
    },
    "nprotect": {
        "name": "nProtect GameGuard",
        "env_var": None,
        "env_val": None,
        "compatible_generally": False,
        "description": "Inkfish. Driver-level. Raramente funciona no Linux/container.",
    },
    "xigncode3": {
        "name": "XIGNCODE3",
        "env_var": None,
        "env_val": None,
        "compatible_generally": False,
        "description": "Wellbia. Detecta máquina virtual/container. Raramente funciona.",
    },
    "ace": {
        "name": "Anti-Cheat Expert",
        "env_var": None,
        "env_val": None,
        "compatible_generally": False,
        "description": "Chinese. Alguns jogos funcionam (Hoyo-verse), outros não (kernel-level).",
    },
    "denuvo": {
        "name": "Denuvo Anti-Cheat / DRM",
        "env_var": None,
        "env_val": None,
        "compatible_generally": True,
        "description": "Denuvo DRM. Geralmente roda. Anti-cheat dedicado é raro.",
    },
    "vanguard": {
        "name": "Riot Vanguard",
        "env_var": None,
        "env_val": None,
        "compatible_generally": False,
        "description": "Riot Games. Kernel-level ring-0. NÃO funciona no Linux.",
    },
    "valve_anti_cheat": {
        "name": "Valve Anti-Cheat (VAC)",
        "env_var": None,
        "env_val": None,
        "compatible_generally": True,
        "description": "Steam VAC. Compatível nativamente com Proton (da Valve).",
    },
    "ricochet": {
        "name": "Ricochet (Activision)",
        "env_var": None,
        "env_val": None,
        "compatible_generally": False,
        "description": "Activision/Blizzard. Kernel-level. NÃO funciona no Linux.",
    },
    "bespoke": {
        "name": "Anti-cheat proprietário",
        "env_var": None,
        "env_val": None,
        "compatible_generally": None,
        "description": "Anti-cheat próprio do jogo. Compatibilidade varia.",
    },
}
